// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slaaubezltjgvuvgsreb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsYWF1YmV6bHRqZ3Z1dmdzcmViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDU3MjgsImV4cCI6MjA1OTc4MTcyOH0.HWUUMvR-p-pE8_eoCqjs17bLEu92g3jTFUW0PN4m85g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);